INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Alajuela',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Atenas',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Grecia',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Guatuso',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Los Chiles',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Naranjo',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Orotina',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Palmares',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Poás',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Río Cuarto',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('San Carlos',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('San Mateo',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('San Ramón',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Sarchí',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Upala',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Zarcero',2);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Alvarado',3);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Cartago',3);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('El Guarco',3);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Jiménez',3);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('La Unión',3);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Oreamuno',3);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Paraíso',3);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Turrialba',3);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Abangares',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Bagaces',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Cañas',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Carrillo',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Hojancha',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('La Cruz',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Liberia',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Nandayure',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Nicoya',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Santa Cruz',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Tilarán',5);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Barva',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Belén',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Flores',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Heredia',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('San Isidro',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('San Pablo',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('San Rafael',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Santa Bárbara',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Santo Domingo',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Sarapiquí',4);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Guácimo',7);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Limón',7);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Matina',7);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Pococí',7);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Siquirres',7);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Talamanca',7);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Buenos Aires',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Corredores',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Coto Brus',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Esparza',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Garabito',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Golfito',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Montes de Oro',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Osa',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Parrita',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Puntarenas',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Quepos',6);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Acosta',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Alajuelita',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Aserrí',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Curridabat',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Desamparados',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Dota',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Escazú',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Goicoechea',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('León Cortés Castro',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Montes de Oca',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Mora',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Moravia',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Pérez Zeledón',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Puriscal',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('San José',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Santa Ana',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Tarrazú',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Tibás',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Turrubares',1);
INSERT INTO Veterinaria_Proyecto.dbo.Canton (nombreCanton, idProvincia) VALUES ('Vásquez de Coronado',1);
